# Generated by Django 2.2 on 2020-05-18 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200518_1041'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Read_Num',
            new_name='ReadNum',
        ),
    ]
