# Generated by Django 2.2 on 2020-05-20 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200518_1153'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReadNum',
        ),
    ]
