# Generated by Django 2.2 on 2020-06-03 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0004_auto_20200602_2039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='like_num',
        ),
    ]
